### ISSUE TITLE
Configure option --disable-log4cxx fails to compile

### ISSUE THREAD

**Issue by odwyer** [RedhawkSDR/framework-core#24]
If the source tree is configured with the "--disable-log4cxx" feature, compilation fails trying to find log4cxx headers.  This is true as of commit 6d72f30 on branch develop-1.10

**Comment by odwyer** [comment]
@shmahon I'm not using this software anymore, but what's the reasoning behind labeling it "wontfix"

**Comment by shmahon** [comment]
**Generally:**  
This baseline has been deprecated since 2016.  The supported baseline can be found at https://github.com/RedhawkSDR/redhawk or, more specifically, https://github.com/RedhawkSDR/core-framework.  A 3.0 version of the REDHAWK SDR is staged for release.  This repo and all its issues should have been archived some years ago.  Since we were seeing more recent traffic on it, I took the liberty of making clear that it is no longer supported to avoid frustration by others.  All issues in this repository are against a software baseline too different from the current to be investigated and fixed.  All unaddressed issues were marked as "wont fix" and closed.

**Specifically**
I honestly don't know why your issue sat un-responded to for 8 years.  A CI pipeline build test was implemented for the core-framework which specifically tested for `--disable-log4cxx` some time after you submitted your ticket.  There is ticketing in the source repos tied to the addition of the test and commensurate fixes, so I'm not sure why your issue wasn't responded to.  That test was automatically run against all release candidates until 11 months ago when it was commented out during a rework of the framework to support Python 3.  Not sure why.  If you have reason to need this feature, please submit the issue under the previously cited repos.
