### ISSUE TITLE
Boost header errors while building RedHawk

### ISSUE THREAD

**Issue by arthurlobo** [RedhawkSDR/framework-core#30]
Hi all:

I am trying to build RedHawk 2.0 SDR framework core on a BeagleBone
Black running Kali Linux 2.0.
gcc version is 4.9.2 (Debian 4.9.2-10)
and Boost version is 1.55.0.2

I get the following partial errors while building. The full list of errors is
in the attached file. Can anyone help?

Making all in framework
make[2]: Entering directory '/root/Downloads/redhawk-src-2.0.0/redhawk/src/base/framework'
  CXX      libossiecf_la-AggregateDevice_impl.lo
  CXX      libossiecf_la-PortSupplier_impl.lo
  CXX      libossiecf_la-PortSet_impl.lo
  CXX      libossiecf_la-Device_impl.lo
  CXX      libossiecf_la-PropertySet_impl.lo
  CXX      libossiecf_la-LifeCycle_impl.lo
  CXX      libossiecf_la-Logging_impl.lo
  CXX      libossiecf_la-Resource_impl.lo
  CXX      libossiecf_la-ThreadedComponent.lo
  CXX      libossiecf_la-ExecutableDevice_impl.lo
  CXX      libossiecf_la-LoadableDevice_impl.lo
  CXX      libossiecf_la-TestableObject_impl.lo
  CXX      libossiecf_la-helperFunctions.lo
  CXX      libossiecf_la-affinity.lo
  CXX      libossiecf_la-Port_impl.lo
  CXX      libossiecf_la-FileStream.lo
  CXX      libossiecf_la-POACreator.lo
  CXX      libossiecf_la-CorbaUtils.lo
  CXX      libossiecf_la-prop_helpers.lo
  CXX      libossiecf_la-MessageInterface.lo
  CXX      libossiecf_la-PropertyInterface.lo
  CXX      libossiecf_la-Service_impl.lo
  CXX      libossiecf_la-type_traits.lo
  CXX      libossiecf_la-AnyUtils.lo
  CXX      logging/libossiecf_la-loghelpers.lo
In file included from /usr/local/include/boost/asio/detail/task_io_service.hpp:207:0,
                 from /usr/local/include/boost/asio/impl/io_service.hpp:71,
                 from /usr/local/include/boost/asio/io_service.hpp:767,
                 from /usr/local/include/boost/asio/basic_io_object.hpp:19,
                 from /usr/local/include/boost/asio/basic_socket.hpp:19,
                 from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20,
                 from /usr/local/include/boost/asio.hpp:20,
                 from logging/loghelpers.cpp:41:
/usr/local/include/boost/asio/detail/impl/task_io_service.hpp:32:6: error: prototype for 'void boost::asio::detail::task_io_service::dispatch(Handler&)' does not match any in class 'boost::asio::detail::task_io_service'
 void task_io_service::dispatch(Handler& handler)
      ^
In file included from /usr/local/include/boost/asio/impl/io_service.hpp:71:0,
                 from /usr/local/include/boost/asio/io_service.hpp:767,
                 from /usr/local/include/boost/asio/basic_io_object.hpp:19,
                 from /usr/local/include/boost/asio/basic_socket.hpp:19,
                 from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20,
                 from /usr/local/include/boost/asio.hpp:20,
                 from logging/loghelpers.cpp:41:
/usr/local/include/boost/asio/detail/task_io_service.hpp:97:8: error: candidate is: template<class Handler> void boost::asio::detail::task_io_service::dispatch(Handler)
   void dispatch(Handler handler);
        ^
In file included from /usr/local/include/boost/asio/detail/task_io_service.hpp:207:0,
                 from /usr/local/include/boost/asio/impl/io_service.hpp:71,
                 from /usr/local/include/boost/asio/io_service.hpp:767,
                 from /usr/local/include/boost/asio/basic_io_object.hpp:19,
                 from /usr/local/include/boost/asio/basic_socket.hpp:19,
                 from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20,
                 from /usr/local/include/boost/asio.hpp:20,
                 from logging/loghelpers.cpp:41:
/usr/local/include/boost/asio/detail/impl/task_io_service.hpp:56:6: error: prototype for 'void boost::asio::detail::task_io_service::post(Handler&)' does not match any in class 'boost::asio::detail::task_io_service'
 void task_io_service::post(Handler& handler)

Best regards,
Art

[redhawk_build_errors.txt](https://github.com/RedhawkSDR/framework-core/files/46493/redhawk_build_errors.txt)

**Comment by bagoulla** [comment]
It looks like this may be a system configuration issue. Based on the location of the boost library (/usr/local/include rather than /usr/include), it looks li



ke you are compiling against a source build of boost, this should work fine however the issue may be that you have multiple versions of boost installed and it is compiling against a different version than you are expecting.  It's hard to tell with the provided info.  When running make, you can run it as "make V=1" to get more verbose output.

I walked through the steps to build the framework for the arm based kali image for the beagle bone black via an arm emulator and did run into some issues which needed to be addressed. Below are the steps I took and I have attached the necessary patches (added as txt files because github seems to only accept txt based text files)

[Fix for g++ 4.9 compile error on Value.cpp](https://github.com/RedhawkSDR/framework-core/files/66818/core_g.4.9-fix.txt)
[Fix for the Message Receiver linker error](https://github.com/RedhawkSDR/framework-core/files/66819/MessageReceiverCpp.txt)



1. I grabbed the beagle bone black image here: https://www.offensive-security.com/kali-linux-vmware-arm-image-download/ and launched it in my qemu based emulator.

2. I found the list of required debian dependencies here:  http://redhawksdr.github.io/Documentation/mainap3.html#x23-410000C and I installed a subset of the dependencies. (I skipped java and xsd due to version conflict addressed below)

    ```
    apt-get install build-essential openmpi-bin libopenmpi-dev python2.7 python2.7-dev uuid uuid-dev libtool autotools-dev autoconf automake python-omniorb omnievents omniidl omniidl-python omniorb omniorb-idl omniorb-nameserver libcos4-dev libomnievents-dev libomniorb4-dev python-numpy python-omniorb liblog4cxx10-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev libboost-thread-dev vim libxml2-utils python-jinja2 libcppunit-dev packagekit-gtk3-module libboost-iostreams-dev
    ```

3. Kali has xsdcxx 4.0 while REDHAWK currently requires 3.3 so I downloaded and installed the xsdcxx 3.3 source from here: http://www.codesynthesis.com/download/xsd/3.3/xsd-3.3.0-2+dep.tar.bz2

4. I cloned the 2.0 framework-core repo, ran the reconf script then ran configure with the parameters specified in the sub100 dollar documentation: 
    ```
    ./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf --disable-java
    ```

It was at this point I received and debugged the compiler error regarding Value.cpp,  and a linking error with MessageReceiver tests. Please see and apply the attached patches which address these issues. 

Other than that, I did not have issues regarding boost. If there is a reason you have boost installed via source please detail your system setup and I can try and reproduce the issue again.
